### PR TITLE
Switch back to python2 to fix issues

### PR DESCRIPTION
**Pull request by ramereth**
It seems as though this app isn't quite python3 compatible yet. This does the
following:

- Switch to using an AlmaLinux 8 so we can use python2
- Install git which is needed for the app to run
- Update requirements.txt to match current production

We need to eventually get this app and it's dependencies upgraded but this at
least allows us to migrate it.

Signed-off-by: Lance Albertson <lance@osuosl.org>

### CODE REVIEW

**Comment by ramereth** [comment]
@nuclearsandwich I ran into an issue when testing this on the new machine. This will fix it so that we can move forward with the migration.

Longer term, you should get this app upgraded to run on python3 properly (including all the deps).

Please merge when you can.

**Review by nuclearsandwich-ai — APPROVED** [review]

**Comment by nuclearsandwich-ai** [comment]
> It seems as though this app isn't quite python3 compatible yet

Thanks for doing the digging here. If I build the python3 container will I be able to see the issues immediately? If not can you leave a couple of reproduction breadcrumbs either here or in an issue so we can take up the python3 work?

**Review by nuclearsandwich — APPROVED** [review]
Second review from my public persona.

**Comment by ramereth** [comment]
> > It seems as though this app isn't quite python3 compatible yet
> 
> Thanks for doing the digging here. If I build the python3 container will I be able to see the issues immediately? If not can you leave a couple of reproduction breadcrumbs either here or in an issue so we can take up the python3 work?

Yes, if you got to the commit before this and do the following:

```
docker build -t prerelease_website .
docker run -it --rm -p 5000:5000 prerelease_website
```

1. Then go open a browser up to http://localhost:5000
2. Click on either release
3. Select a repo (any repo) then click next
4. Click next again

This is where it breaks. If you look at the output of the container you'll see a stack trace. I did go through originally and use 2to3 to convert some files in this repo, but it seems some of the other dependent ros python libraries might need fixing.

**Pull request merged**
