### PR TITLE
handle non-devel repositories correctly

### LINKED ISSUE #31: Generated commands look the same no matter what branch option selected
(May or may not be related to #14)

I flipped `devel` and `latest` but in the end I seem to have gotten the exactly same command.
- devel: `generate_prerelease_script.py https://raw.githubusercontent.com/ros-infrastructure/ros_buildfarm_config/production/index.yaml jade default ubuntu trusty amd64 moveit_core --level 0 --output-dir .`
- latest: `generate_prerelease_script.py https://raw.githubusercontent.com/ros-infrastructure/ros_buildfarm_config/production/index.yaml jade default ubuntu trusty amd64 moveit_core --level 0 --output-dir .`

Also chose specific version tag but it looks the same again.
- 0.6.15: `generate_prerelease_script.py https://raw.githubusercontent.com/ros-infrastructure/ros_buildfarm_config/production/index.yaml jade default ubuntu trusty amd64 moveit_core --level 0 --output-dir .`

Question: Will the result of these command be actually different with these commands (if so, the change is embedded somehow somewhere invisible from the command)?

### PR DESCRIPTION
**Pull request by wjwwood**
fixes #31

@dirk-thomas can you review this?

This is the output of a generated command with:

- `serial`: `1.2.1-0`
- `nodelet_core`: `latest`
- `actionlib`: `devel`

```
generate_prerelease_script.py \
  https://raw.githubusercontent.com/ros-infrastructure/ros_buildfarm_config/production/index.yaml \
  kinetic default ubuntu xenial amd64 \
  actionlib \
  --custom-repo serial:git:https://github.com/wjwwood/serial-release.git:release/kinetic/serial/1.2.1-0 \
  --custom-repo nodelet_topic_tools:git:https://github.com/ros-gbp/nodelet_core-release.git:release/kinetic/nodelet_topic_tools \
  --custom-repo nodelet_core:git:https://github.com/ros-gbp/nodelet_core-release.git:release/kinetic/nodelet_core \
  --custom-repo nodelet:git:https://github.com/ros-gbp/nodelet_core-release.git:release/kinetic/nodelet \
  --level 1 \
  --output-dir ./
```

I'm still running a few of the generated prerelease commands locally, but they look like they're working and that they cloned the right things.

### CODE REVIEW

**Comment by dirk-thomas** [comment]
The command line only needs to mention `--custom-repo` once and it can be followed by `*` repositories (see https://github.com/ros-infrastructure/ros_buildfarm/blob/bb5e13bb16bed6724f4f0a0a5ba2b2896bc9dd7a/scripts/prerelease/generate_prerelease_script.py#L77-L84). I haven't tried to pass it multiple times. But if that works for you it looks good to me.

**Comment by wjwwood** [comment]
It doesn't :smile:. I'll have to modify it to send `--custom-repo` just once.

**Comment by wjwwood** [comment]
Ok now with e376511 it looks like this:

```
generate_prerelease_script.py \
  https://raw.githubusercontent.com/ros-infrastructure/ros_buildfarm_config/production/index.yaml \
  kinetic default ubuntu xenial amd64 \
  actionlib \
  --custom-repo \
    serial:git:https://github.com/wjwwood/serial-release.git:release/kinetic/serial/1.2.1-0 \
    nodelet_topic_tools:git:https://github.com/ros-gbp/nodelet_core-release.git:release/kinetic/nodelet_topic_tools \
    nodelet_core:git:https://github.com/ros-gbp/nodelet_core-release.git:release/kinetic/nodelet_core \
    nodelet:git:https://github.com/ros-gbp/nodelet_core-release.git:release/kinetic/nodelet \
  --level 1 \
  --output-dir ./
```

**Comment by wjwwood** [comment]
That looks right locally now.

**Comment by wjwwood** [comment]
deployed

**Pull request merged**
