### PR TITLE
Add in the actual melodic logo.

### PR DESCRIPTION
**Pull request by clalancette**
Also switch the background on the column so it is the "correct" one from the rest of the artwork.

Signed-off-by: Chris Lalancette <clalancette@openrobotics.org>

### CODE REVIEW

**Comment by wjwwood** [comment]
Seems reasonable to me, but I did not have time to try it out locally today.

**Comment by clalancette** [comment]
This is fairly low-risk, so I'm just going to merge it.  We can change things later if we run into problems.

**Comment by mikaelarguedas** [comment]
@clalancette FYI this doesn't seem to have been deployed

**Comment by clalancette** [comment]
> @clalancette FYI this doesn't seem to have been deployed

Thanks, deployed now.

**Pull request merged**
