### PR TITLE
update the default build farm config url

### LINKED ISSUE #25: prerelease website defaults to the wrong build farm config for build.ros.org
Currently it defaults to:

https://raw.githubusercontent.com/ros-infrastructure/ros_buildfarm_config/master/index.yaml

Which is a file on the master branch, but the build farm uses the production branch. This is configurable, but the default should probably point at:

https://raw.githubusercontent.com/ros-infrastructure/ros_buildfarm_config/production/index.yaml

### PR DESCRIPTION
**Pull request by wjwwood**
Fixes #25

### CODE REVIEW

**Comment by wjwwood** [comment]
@jacquelinekay can you review and then deploy this?

**Comment by jacquelinekay** [comment]
how should I install python-ros-buildfarm so that I can test the prerelease command on Xenial?

**Comment by wjwwood** [comment]
You'll need to get the default branch of this repository, and install it into a virtualenv. And then you can continue as normal.

**Comment by wjwwood** [comment]
Not this repository, rather this one: https://github.com/ros-infrastructure/ros_buildfarm

**Comment by dirk-thomas** [comment]
I just released 1.1.0 of `ros_buildfarm`.

- Dirk

**Comment by wjwwood** [comment]
Thanks, testing on my Xenial VM right now, someone else should try it out on Trusty for some variety.

**Comment by jacquelinekay** [comment]
oh oops I'm trying it on xenial right now

**Comment by wjwwood** [comment]
I can try on my Trusty VM too, afterwards.

**Comment by wjwwood** [comment]
Actually, I didn't have docker installed in my Xenail VM and it doesn't look like they have released yet. So I'm just going to try on Trusty.

**Comment by jacquelinekay** [comment]
Yeah, with regards to installing docker, when adding the deb sources I just replaced the distro name with "xenial and it worked.

anyway, the prerelease command worked! +1

**Comment by wjwwood** [comment]
Worked for me too.

**Comment by wjwwood** [comment]
@jacquelinekay can you merge this and deploy it?

**Comment by jacquelinekay** [comment]
Going to merge #27 (adds the logo) and deploy that too

**Pull request merged**
