### PR TITLE
Add Noetic to Prerelease website

### PR DESCRIPTION
**Pull request by sloretz**
It seems to work locally. It generated a prerelease command for Noetic that appears to be doing the right thing on my machine. The logo image is a placeholder since it hasn't been announced yet.

Modeled after #47 which added Melodic

### CODE REVIEW

**Comment by sloretz** [comment]
Friendly ping @wjwwood . Are you the `prerelease_website` maintainer? If so, what does this PR need to get deployed?

**Comment by wjwwood** [comment]
I don't consider myself the maintainer of this repository but I was one of the original authors of the current version. Looking at the commit history each ROS boss tended contribute in turn. I will review this for you though.

As for deployment, I don't actually remember. The README describes what is required to set it up, and I assume it is on ros.org which is an OSU server, so maybe just go ther and git pull?

**Comment by clalancette** [comment]
> As for deployment, I don't actually remember. The README describes what is required to set it up, and I assume it is on ros.org which is an OSU server, so maybe just go there and git pull?

I *think* that is the case, but I also don't remember from 2 years ago :(.  Maybe @tfoote knows for sure?

**Comment by sloretz** [comment]
Thanks @wjwwood ! I'll merge this and search around for how to deploy it

**Comment by sloretz** [comment]
> Thanks @wjwwood ! I'll merge this and search around for how to deploy it

Deployed. Process was

1) Ask @tfoote to add my ssh key
2) ssh in, `git pull` in `/var/www/prerelease_website`
3) execute `~/reload_httpd`

**Pull request merged**
